name: Robot Framework Tests WEB
 
on: push
 
jobs:
  test_web:
    name: Web Tests - Robot
    runs-on: ubuntu-latest

    # Permissões e Ambiente para disponibilizar o Reporte de Testes no GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://jvluzc.github.io/qa-orangehrm-automation-joao-vitor-condidorio/report.html

    steps:
      - name: Etapa 1 - Clonar Repositório do Projeto para a Máquina Virtual do GitHub Actions
        # run: echo clonando para o repositorio na maquina virtual
        uses: actions/checkout@v4
 

      - name: Etapa 2 - Instalação do Python
        # run: echo Instalação da versão 3.12 do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
 

      - name: Etapa 3 - Instalação das Depedências do Projeto
        # run: echo Instalação das depedências do Projeto
        run: |
          pip install setuptools
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-faker


      - name: Etapa 4 - Criar pasta de resultados
        run: mkdir -p results/
        if: always()
 

      - name: Etapa 5 - Executar Testes Web do Robot Framework
        # run: echo Executando os testes de API do Robot
        continue-on-error: true  # não falha o job aqui
        run: |
          robot --outputdir results/ tests/

      
      # - name: Etapa 5.5 - Criar um report.html falso se não foi gerado
      #   if: always()
      #   run: |
      #     if [ ! -f results/report.html ]; then
      #       echo "<html><body><h1 style='color:red'>❌ Nenhum relatório gerado</h1><p>Os testes falharam antes da geração do relatório. Verifique os logs da pipeline no GitHub Actions.</p></body></html>" > results/report.html
      #     fi


      - name: Etapa 6 - Salvar Relatórios dos Testes Executados
        # run: echo Salvando o Report dos Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report
          path: results/


      - name: Etapa 7 - Configurar GitHub Pages para Hospedagem dos Relatórios
        uses: actions/configure-pages@v5
 

      - name: Etapa 8 - Fazer Upload dos Relatórios Gerados
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: results/
 
          
      - name: Etapa 9 - Publicar Relatórios de Testes no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4